### ISSUE TITLE
ValueError: could not broadcast input array from shape (1,96,25) into shape (1,96,32)

### ISSUE THREAD

**Issue by manbharae** [drscotthawley/audio-classifier-keras-cnn#2]
Dear Professor, Thank you for the excellent tutorial.

For sample data, i created two folders and put one set of sounds in each folder.

Step 1 went well.
```
man@man:~/Downloads/audio-classifier-keras-cnn-master$ python preprocess_data.py 
class_names =  ['tring', 'hold']
 class name = tring          -   0, 9 files in this class
 Loading class: tring          ( 1 of  2 classes), file 1 of 9: Samples/tring/r4.wav
 class name = hold           -   1, 94 files in this class
 Loading class: hold           ( 2 of  2 classes), file 1 of 94: Samples/hold/hm1_081.mp3
 Loading class: hold           ( 2 of  2 classes), file 21 of 94: Samples/hold/hm1_011.mp3
 Loading class: hold           ( 2 of  2 classes), file 41 of 94: Samples/hold/hm1_020.mp3
 Loading class: hold           ( 2 of  2 classes), file 61 of 94: Samples/hold/hm1_077.mp3
 Loading class: hold           ( 2 of  2 classes), file 81 of 94: Samples/hold/hm1_043.mp3
```

**STEP TWO ERROR**
```
man@man:~/Downloads/audio-classifier-keras-cnn-master$ python train_network.py
Using TensorFlow backend.
class_names =  ['tring', 'hold']
total files =  103
   get_sample_dimensions: melgram.shape =  (1, 1, 96, 32)

 Loading class: tring          ( 1 of  2 classes), file 1 of 9: Preproc/tring/r6.wav.npy
Traceback (most recent call last):
  File "train_network.py", line 201, in <module>
    X_train, Y_train, paths_train, X_test, Y_test, paths_test, class_names, sr = build_datasets(preproc=True)
  File "train_network.py", line 147, in build_datasets
    X_train[train_count,:,:] = melgram
ValueError: could not broadcast input array from shape (1,96,25) into shape (1,96,32)
man@man:~/Downloads/audio-classifier-keras-cnn-master$ 

```

What is meant by ```ValueError: could not broadcast input array from shape (1,96,25) into shape (1,96,32)``` How do I resolve it?

**Comment by haikuoyao** [comment]
Don't know whether you've solved it. 
If not, give a try on this 
```
from keras import backend as K
K.set_image_dim_ordering('th')
```

**Comment by apal21** [comment]
I'm also getting the same error.
`get_sample_dimensions: melgram.shape =  (1, 1, 96, 216)`

&
```
in build_datasets X_train[train_count, :, :] = melgram
ValueError: could not broadcast input array from shape (1,96,198) into shape (1,96,216)
```

and this solution `K.set_image_dim_ordering('th')` didn't work for me. I also tried 'tf'.

**Comment by apal21** [comment]
Actually I can run this code without any error if I pass `duration=4.0` inside `librosa.load()` in `preprocess_data.py` but I have the audio files with random length. 
So can you please show me how to do that? 
Thanks.

**Comment by drscotthawley** [comment]
@apal21 et al:

Guys, as it says in the README: 

"This code is NOT being maintained. Your Issues will be ignored. For up-to-date code, switch over to Panotti."

https://github.com/drscotthawley/panotti

How can I make this more clear?
